global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'fastapi-app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:8000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __address__
        replacement: 'app:8000'
      - source_labels: [__metrics_path__]
        target_label: __metrics_path__
        regex: (.+)
        replacement: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
